name: Container Test 

on: 
  workflow_dispatch:

jobs:

  vm-test:
    runs-on: ubuntu-latest 
    
    steps:
      - name: show user
        run: id

  container-test:
    runs-on: ubuntu-latest 
    container:
      image: node:16-alpine3.11      

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Info
        run: |
          whoami
          cat /etc/passwd
          cat /etc/os-release
          ls -al
      
