name: Container Test 

on: 
  workflow_dispatch:

jobs:

  vm-test:
    runs-on: ubuntu-latest 
    
    steps:
      - name: show user
        run: |
          id
          env | sort

  container-test:
    runs-on: ubuntu-latest 
    container:
      image: node:16-alpine3.11
      ## or force container to run as the VM user `runner (1001)`
      ## https://github.com/actions/runner/issues/691 is a more polished version that doesn't assume 1001
      ## options: --user 1001

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          path: foo

      - name: Show Info
        run: |
          id
          ls -alR
